package dev.komsay.panindamobile

import android.os.Build
import android.os.Bundle
import android.widget.ImageButton
import android.widget.LinearLayout
import androidx.activity.enableEdgeToEdge
import androidx.annotation.RequiresApi
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import dev.komsay.panindamobile.ui.components.NavigationBarManager
import dev.komsay.panindamobile.ui.components.ProductInventoryComponent
import dev.komsay.panindamobile.ui.data.Product
import dev.komsay.panindamobile.ui.fragments.AddProductDialogFragment
import dev.komsay.panindamobile.ui.utils.DataHelper

class InventoryPage : AppCompatActivity() {

    private lateinit var dataHelper: DataHelper
    private lateinit var productContainer: LinearLayout
    private lateinit var categoryContainer: LinearLayout
    private lateinit var products: List<Product>


    @RequiresApi(Build.VERSION_CODES.O)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_inventory_page)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.inventoryPage)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }

        val app = application as Paninda
        dataHelper = app.dataHelper
        productContainer = findViewById(R.id.productInventoryContainer)
        categoryContainer = findViewById(R.id.categorySlider)

        val addBtn = findViewById<ImageButton>(R.id.addBtn)

        addBtn.setOnClickListener {
            val addProductDialog = AddProductDialogFragment()
            addProductDialog.setOnProductAddedListener { name, price, stock, category ->
                val newProduct = Product(
                    id = "", // ID will be generated by DataHelper
                    name = name,
                    price = price.toDouble(),
                    stock = stock.toInt(),
                    category = category
                )
                dataHelper.addProduct(newProduct)
                // Refresh the list
                refreshProductList()
            }
            addProductDialog.show(supportFragmentManager, "AddProductDialogFragment")
        }

        refreshProductList()

        val navigationBarManager = NavigationBarManager(this, findViewById(R.id.navbar))
        navigationBarManager.setup()
    }

    @RequiresApi(Build.VERSION_CODES.O)
    private fun refreshProductList() {
        productContainer.removeAllViews()
        val products = dataHelper.getAllProducts()
        for (product in products) {
            val component = ProductInventoryComponent(productContainer, this)
            component.bind(product) {
                // This is the callback for when a product is updated.
                refreshProductList()
            }
        }
    }

    private fun refreshCategoryList() {
        categoryContainer.removeAllViews()

    }
}
